spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        web: debug
        cache: debug
      ehcache: debug

jwt:
  secret:
    key: "d937bdc3fdc680aa08cd427e935c1c50cc8dd14415bc8a707dc6adf6bea615ce"
  expiration: 86400000 # a day