
logging:
  config: classpath:logback-spring-dev.xml
  level:
    root: INFO
  file:
    path: ${LOG_PATH:/tmp/logs}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg [corr=%X{correlationId}]%n"
